/*
 * Copyright (c) 2020, MIPI Alliance, Inc.
 * Copyright (c) 2026 ASPEED Technology Inc.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Ported to Zephyr from the Linux mipi-i3c-hci driver
 * (drivers/i3c/master/mipi-i3c-hci/).
 */

#ifndef ZEPHYR_DRIVERS_I3C_MIPI_HCI_XFER_MODE_RATE_H_
#define ZEPHYR_DRIVERS_I3C_MIPI_HCI_XFER_MODE_RATE_H_

#include <zephyr/sys/util.h>

#define XFERMODE_IDX_I3C_SDR 0x00
#define XFERMODE_IDX_I3C_HDR_DDR 0x01
#define XFERMODE_IDX_I3C_HDR_T 0x02
#define XFERMODE_IDX_I3C_HDR_BT 0x03
#define XFERMODE_IDX_I2C 0x08

#define XFERMODE_VALID_XFER_ADD_FUNC GENMASK(21, 16)
#define XFERMODE_ML_DATA_XFER_CODING GENMASK(15, 11)
#define XFERMODE_ML_ADDL_LANES GENMASK(10, 8)
#define XFERMODE_SUPPORTED BIT(7)
#define XFERMODE_MODE GENMASK(3, 0)

#define XFERRATE_I3C_SDR0 0x00
#define XFERRATE_I3C_SDR1 0x01
#define XFERRATE_I3C_SDR2 0x02
#define XFERRATE_I3C_SDR3 0x03
#define XFERRATE_I3C_SDR4 0x04
#define XFERRATE_I3C_SDR_FM_FMP 0x05
#define XFERRATE_I3C_SDR_USER6 0x06
#define XFERRATE_I3C_SDR_USER7 0x07

#define XFERRATE_I2C_FM 0x00
#define XFERRATE_I2C_FMP 0x01
#define XFERRATE_I2C_USER2 0x02
#define XFERRATE_I2C_USER3 0x03
#define XFERRATE_I2C_USER4 0x04
#define XFERRATE_I2C_USER5 0x05
#define XFERRATE_I2C_USER6 0x06
#define XFERRATE_I2C_USER7 0x07

#define XFERRATE_MODE_I3C 0x00
#define XFERRATE_MODE_I2C 0x08

#define XFERRATE_MODE_ID GENMASK(31, 28)
#define XFERRATE_RATE_ID GENMASK(22, 20)
#define XFERRATE_ACTUAL_RATE_KHZ GENMASK(19, 0)

#endif /* ZEPHYR_DRIVERS_I3C_MIPI_HCI_XFER_MODE_RATE_H_ */
