/*
 * Copyright (c) 2020 ASPEED
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_AST1030_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_AST1030_H_

#define ASPEED_CLK_PCLK		0
#define ASPEED_CLK_HCLK		1
#define ASPEED_CLK_UART1	2
#define ASPEED_CLK_UART2	3
#define ASPEED_CLK_UART3	4
#define ASPEED_CLK_UART4	5
#define ASPEED_CLK_UART5	6
#define ASPEED_CLK_UART6	7
#define ASPEED_CLK_UART7	8
#define ASPEED_CLK_UART8	9
#define ASPEED_CLK_UART9	10
#define ASPEED_CLK_UART10	11
#define ASPEED_CLK_UART11	12
#define ASPEED_CLK_UART12	13
#define ASPEED_CLK_UART13	14

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_AST1030_H_ */
