/*
 * Copyright (c) 2020 ASPEED
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_AST26XX_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_AST26XX_H_

#define ASPEED_CLK_GATE_MCLK		0
#define ASPEED_CLK_GATE_ECLK		1
#define ASPEED_CLK_GATE_GCLK		2
#define ASPEED_CLK_GATE_VCLK		3
#define ASPEED_CLK_GATE_BCLK		4
#define ASPEED_CLK_GATE_DCLK		5
#define ASPEED_CLK_GATE_REF0CLK		6
#define ASPEED_CLK_GATE_USBPORT2CLK	7
/* bit[8] is reserved */
#define ASPEED_CLK_GATE_USBUHCICLK	9
#define ASPEED_CLK_GATE_D1CLK		10
/* bit[12:11] are reserved */
#define ASPEED_CLK_GATE_YCLK		13
#define ASPEED_CLK_GATE_USBPORT1CLK	14
#define ASPEED_CLK_GATE_UART5CLK	15
/* bit[19:16] are reserved */
#define ASPEED_CLK_GATE_MAC1CLK		20
#define ASPEED_CLK_GATE_MAC2CLK		21
/* bit[23:22] are reserved */
#define ASPEED_CLK_GATE_RSACLK		24
#define ASPEED_CLK_GATE_RVASCLK		25
/* bit[26] is reserved */
#define ASPEED_CLK_GATE_EMMCCLK		27
/* bit[31:28] are reserved */

#define ASPEED_CLK_GATE_LCLK		(32 + 0)
#define ASPEED_CLK_GATE_ESPICLK		(32 + 1)
#define ASPEED_CLK_GATE_REF1CLK		(32 + 2)
/* bit[3] is reserved */
#define ASPEED_CLK_GATE_SDCLK		(32 + 4)
#define ASPEED_CLK_GATE_LHCCLK		(32 + 5)
/* bit[6] is reserved */
#define ASPEED_CLK_GATE_I3CDMACLK	(32 + 7)
#define ASPEED_CLK_GATE_I3C0CLK		(32 + 8)
#define ASPEED_CLK_GATE_I3C1CLK		(32 + 9)
#define ASPEED_CLK_GATE_I3C2CLK		(32 + 10)
#define ASPEED_CLK_GATE_I3C3CLK		(32 + 11)
#define ASPEED_CLK_GATE_I3C4CLK		(32 + 12)
#define ASPEED_CLK_GATE_I3C5CLK		(32 + 13)
/* bit[15:14] are reserved */
#define ASPEED_CLK_GATE_UART1CLK	(32 + 16)
#define ASPEED_CLK_GATE_UART2CLK	(32 + 17)
#define ASPEED_CLK_GATE_UART3CLK	(32 + 18)
#define ASPEED_CLK_GATE_UART4CLK	(32 + 19)
#define ASPEED_CLK_GATE_MAC3CLK		(32 + 20)
#define ASPEED_CLK_GATE_MAC4CLK		(32 + 21)
#define ASPEED_CLK_GATE_UART6CLK	(32 + 22)
#define ASPEED_CLK_GATE_UART7CLK	(32 + 23)
#define ASPEED_CLK_GATE_UART8CLK	(32 + 24)
#define ASPEED_CLK_GATE_UART9CLK	(32 + 25)
#define ASPEED_CLK_GATE_UART10CLK	(32 + 26)
#define ASPEED_CLK_GATE_UART11CLK	(32 + 27)
#define ASPEED_CLK_GATE_UART12CLK	(32 + 28)
#define ASPEED_CLK_GATE_UART13CLK	(32 + 29)
#define ASPEED_CLK_GATE_FSICLK		(32 + 30)


#define ASPEED_CLK_PCLK		0
#define ASPEED_CLK_HCLK		1
#define ASPEED_CLK_UART1	2
#define ASPEED_CLK_UART2	3
#define ASPEED_CLK_UART3	4
#define ASPEED_CLK_UART4	5
#define ASPEED_CLK_UART5	6
#define ASPEED_CLK_UART6	7
#define ASPEED_CLK_UART7	8
#define ASPEED_CLK_UART8	9
#define ASPEED_CLK_UART9	10
#define ASPEED_CLK_UART10	11
#define ASPEED_CLK_UART11	12
#define ASPEED_CLK_UART12	13
#define ASPEED_CLK_UART13	14
#define ASPEED_CLK_APB1		15
#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_AST26XX_H_ */
