/*
 * Copyright (c) 2026 ASPEED Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_AST10X0_G2_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_AST10X0_G2_H_

/* SCU240: Clock Stop Control 1 */
#define SCU1_CLK_GATE_LCLK		0
#define SCU1_CLK_GATE_ESPICLK		2
#define SCU1_CLK_GATE_REFCLK		6
#define SCU1_CLK_GATE_UART0CLK		11
#define SCU1_CLK_GATE_UART1CLK		12
#define SCU1_CLK_GATE_UART2CLK		13
#define SCU1_CLK_GATE_UART3CLK		14
#define SCU1_CLK_GATE_I2CCLK		15
#define SCU1_CLK_GATE_I3C0CLK		16
#define SCU1_CLK_GATE_I3C1CLK		17
#define SCU1_CLK_GATE_I3C2CLK		18
#define SCU1_CLK_GATE_I3C3CLK		19
#define SCU1_CLK_GATE_I3C4CLK		20
#define SCU1_CLK_GATE_I3C5CLK		21
#define SCU1_CLK_GATE_I3C6CLK		22
#define SCU1_CLK_GATE_I3C7CLK		23

/* SCU260: Clock Stop Control 2 */
#define SCU1_CLK_GATE_UART5CLK		(32 + 0)
#define SCU1_CLK_GATE_UART6CLK		(32 + 1)
#define SCU1_CLK_GATE_UART7CLK		(32 + 2)
#define SCU1_CLK_GATE_UART8CLK		(32 + 3)
#define SCU1_CLK_GATE_UART9CLK		(32 + 4)
#define SCU1_CLK_GATE_UART10CLK		(32 + 5)
#define SCU1_CLK_GATE_UART11CLK		(32 + 6)
#define SCU1_CLK_GATE_UART12CLK		(32 + 7)
#define SCU1_CLK_GATE_UHCICLK		(32 + 12)
#define SCU1_CLK_GATE_USB2ACLK		(32 + 17)
#define SCU1_CLK_GATE_USB2BCLK		(32 + 18)

#define SCU1_CLK_GATE_NUM		(SCU1_CLK_GATE_USB2BCLK + 1)

/* Derived clocks */
#define SCU1_CLKIN			(SCU1_CLK_GATE_NUM + 0)
#define SCU1_CLK_HPLL			(SCU1_CLK_GATE_NUM + 1)
#define SCU1_CLK_UXCLK			(SCU1_CLK_GATE_NUM + 2)
#define SCU1_CLK_HUXCLK			(SCU1_CLK_GATE_NUM + 3)
#define SCU1_CLK_UARTX			(SCU1_CLK_GATE_NUM + 4)
#define SCU1_CLK_HUARTX			(SCU1_CLK_GATE_NUM + 5)
#define SCU1_CLK_AHB			(SCU1_CLK_GATE_NUM + 6)
#define SCU1_CLK_APB			(SCU1_CLK_GATE_NUM + 7)
#define SCU1_CLK_MEMCLK			(SCU1_CLK_GATE_NUM + 8)
#define SCU1_CLK_SPIS0			(SCU1_CLK_GATE_NUM + 9)
#define SCU1_CLK_SPIS1			(SCU1_CLK_GATE_NUM + 10)
#define SCU1_CLK_PECI			(SCU1_CLK_GATE_NUM + 11)
#define SCU1_CLK_SSP			(SCU1_CLK_GATE_NUM + 12)
#define SCU1_CLK_PSP			(SCU1_CLK_GATE_NUM + 13)
#define SCU1_CLK_UART4			(SCU1_CLK_GATE_NUM + 14)
#define SCU1_CLK_I3C			(SCU1_CLK_GATE_NUM + 15)

/* Datasheet clock-domain names. */
#define SCU1_CLK_HCLK			SCU1_CLK_AHB
#define SCU1_CLK_PCLK			SCU1_CLK_APB
#define SCU1_CLK_SPI0			SCU1_CLK_SPIS0
#define SCU1_CLK_SPI1			SCU1_CLK_SPIS1
#define SCU1_CLK_UART0			SCU1_CLK_GATE_UART0CLK
#define SCU1_CLK_UART1			SCU1_CLK_GATE_UART1CLK
#define SCU1_CLK_UART2			SCU1_CLK_GATE_UART2CLK
#define SCU1_CLK_UART3			SCU1_CLK_GATE_UART3CLK
#define SCU1_CLK_UART5			SCU1_CLK_GATE_UART5CLK
#define SCU1_CLK_UART6			SCU1_CLK_GATE_UART6CLK
#define SCU1_CLK_UART7			SCU1_CLK_GATE_UART7CLK
#define SCU1_CLK_UART8			SCU1_CLK_GATE_UART8CLK
#define SCU1_CLK_UART9			SCU1_CLK_GATE_UART9CLK
#define SCU1_CLK_UART10			SCU1_CLK_GATE_UART10CLK
#define SCU1_CLK_UART11			SCU1_CLK_GATE_UART11CLK
#define SCU1_CLK_UART12			SCU1_CLK_GATE_UART12CLK

#define SCU1_NUM_CLKS			(SCU1_CLK_I3C + 1)

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_AST10X0_G2_H_ */
