/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright (c) 2025 ASPEED Technology Inc.
 */

#ifndef ZEPHYR_DRIVERS_MISC_ASPEED_CPTRA_IPC_H_
#define ZEPHYR_DRIVERS_MISC_ASPEED_CPTRA_IPC_H_

#include <zephyr/types.h>
#include <zephyr/device.h>

enum cptra_ipc_cmd {
	CPTRA_IPCCMD_ECDSA384_SIGNATURE_VERIFY = 0,
	CPTRA_IPCCMD_SHA384,
	CPTRA_IPCCMD_LMS_SIGNATURE_VERIFY,
	CPTRA_IPCCMD_CALIPTRA_FW_LOAD,
	CPTRA_IPCCMD_STASH_MEASUREMENT,
	CPTRA_IPCCMD_QUOTE_PCRS,
	CPTRA_IPCCMD_GET_IDEV_CERT,
	CPTRA_IPCCMD_GET_IDEV_INFO,
	CPTRA_IPCCMD_POPULATE_IDEV_CERT,
	CPTRA_IPCCMD_GET_LDEV_CERT,
	CPTRA_IPCCMD_GET_FMC_ALIAS_CERT,
	CPTRA_IPCCMD_GET_RT_ALIAS_CERT,
	CPTRA_IPCCMD_INVOKE_DPE_COMMAND,
	CPTRA_IPCCMD_DISABLE_ATTESTATION,
	CPTRA_IPCCMD_FW_INFO,
	CPTRA_IPCCMD_DPE_TAG_TCI,
	CPTRA_IPCCMD_DPE_GET_TAGGED_TCI,
	CPTRA_IPCCMD_INCREMENT_PCR_RESET_COUNTER,
	CPTRA_IPCCMD_EXTEND_PCR,
	CPTRA_IPCCMD_ADD_SUBJECT_ALT_NAME,
	CPTRA_IPCCMD_CERTIFY_KEY_EXTENDED,
	CPTRA_IPCCMD_FIPS_VERSION,
	CPTRA_IPCCMD_SHUTDOWN,
	CPTRA_IPCCMD_CAPABILITIES,
};

int cptra_ipc_enable(void);

#endif /* ZEPHYR_DRIVERS_MISC_ASPEED_CPTRA_IPC_H_ */
