CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_ALWAYS_RUNTIME=y
# CONFIG_LOAD_FIT_ENABLED=y
CONFIG_AST_EXT_LOADER_ADDR=0x14b9e000
CONFIG_LOAD_FIT_ADDR=0x20120000
CONFIG_IPC_SAMPLE=y
CONFIG_LTPI=y
CONFIG_MAIN_STACK_SIZE=4096