/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright (c) 2023 ASPEED Technology Inc.
 */

/*
 * Generated by info2header.py
 * Do not edit it.
 */
#ifndef ZEPHYR_INCLUDE_DRIVERS_MISC_OTP_INFO_10X0_H_
#define ZEPHYR_INCLUDE_DRIVERS_MISC_OTP_INFO_10X0_H_

#define OTP_INFO_VER		"2.0.1"
#define OTP_REG_RESERVED	-1
#define OTP_REG_VALUE		-2
#define OTP_REG_VALID_BIT	-3

struct otpstrap_info {
	signed char bit_offset;
	signed char length;
	signed char value;
	const char *information;
};

struct otpconf_info {
	signed char dw_offset;
	signed char bit_offset;
	signed char length;
	signed char value;
	const char *information;
};

struct scu_info {
	signed char bit_offset;
	signed char length;
	const char *information;
};

static const struct scu_info ast1030a0_scu_info[] = {
	{ 0, 1, "Disable ARM CM4 CPU boot (TXD5)" },
	{ 1, 2, "Reserved" },
	{ 3, 1, "Address offset of single chip ABR mode" },
	{ 4, 13, "Reserved" },
	{ 17, 1, "Disabl3 ARM JTAG debug" },
	{ 18, 14, "Reserved" },
	{ 32, 4, "Reserved" },
	{ 36, 1, "Disable debug interfaces" },
	{ 37, 3, "Reserved" },
	{ 40, 1, "Enable boot from Uart5 by Pin Strap" },
	{ 41, 2, "Reserved" },
	{ 43, 1, "Enable boot SPI ABR" },
	{ 44, 1, "Boot SPI ABR Mode" },
	{ 45, 3, "Boot SPI flash size" },
	{ 48, 6, "Reserved" },
	{ 54, 1, "Enable boot SPI auxiliary control pins" },
	{ 57, 7, "Reserved" },
	{ 62, 1, "Enable dedicate GPIO strap pins" },
	{ 63, 1, "Enable Secure Boot by Pin Strap" }
};

static const struct otpstrap_info ast1030a0_strap_info[] = {
	{ 0, 1, 0, "Disable Secure Boot" },
	{ 0, 1, 1, "Enable Secure Boot" },
	{ 1, 2, OTP_REG_RESERVED, "Reserved" },
	{ 3, 1, 0, "Address offset of single chip ABR mode : 1/2" },
	{ 3, 1, 1, "Address offset of single chip ABR mode : 1/3" },
	{ 4, 13, OTP_REG_RESERVED, "Reserved" },
	{ 17, 1, 0, "Enable ARM JTAG debug" },
	{ 17, 1, 1, "Disable ARM JTAG debug" },
	{ 18, 14, OTP_REG_RESERVED, "Reserved" },
	{ 32, 4, OTP_REG_RESERVED, "Reserved" },
	{ 36, 1, 0, "Enable debug interfaces" },
	{ 36, 1, 1, "Disable debug interfaces" },
	{ 37, 3, OTP_REG_RESERVED, "Reserved" },
	{ 40, 1, 0, "Disable boot from uart5" },
	{ 40, 1, 1, "Enable boot from uart5" },
	{ 41, 2, OTP_REG_RESERVED, "Reserved" },
	{ 43, 1, 0, "Disable boot SPI ABR" },
	{ 43, 1, 1, "Enable boot SPI ABR" },
	{ 44, 1, 0, "Boot SPI ABR Mode : dual" },
	{ 44, 1, 1, "Boot SPI ABR Mode : single" },
	{ 45, 3, 0, "Boot SPI flash size : 0MB" },
	{ 45, 3, 1, "Boot SPI flash size : 1MB" },
	{ 45, 3, 2, "Boot SPI flash size : 2MB" },
	{ 45, 3, 3, "Boot SPI flash size : 4MB" },
	{ 45, 3, 4, "Boot SPI flash size : 8MB" },
	{ 45, 3, 5, "Boot SPI flash size : 16MB" },
	{ 45, 3, 6, "Boot SPI flash size : 32MB" },
	{ 45, 3, 7, "Boot SPI flash size : 64MB" },
	{ 48, 6, OTP_REG_RESERVED, "Reserved" },
	{ 54, 1, 0, "Disable boot SPI auxiliary control pins" },
	{ 54, 1, 1, "Enable boot SPI auxiliary control pins" },
	{ 57, 7, OTP_REG_RESERVED, "Reserved" },
	{ 62, 1, 0, "Disable dedicate GPIO strap pins" },
	{ 62, 1, 1, "Enable dedicate GPIO strap pins" },
	{ 63, 1, OTP_REG_RESERVED, "Reserved" }
};

static const struct otpconf_info ast1030a0_conf_info[] = {
	{ 0, 1, 1, 0, "Disable Secure Boot" },
	{ 0, 1, 1, 1, "Enable Secure Boot" },
	{ 0, 3, 1, 0, "User region ECC disable" },
	{ 0, 3, 1, 1, "User region ECC enable" },
	{ 0, 4, 1, 0, "Secure Region ECC disable" },
	{ 0, 4, 1, 1, "Secure Region ECC enable" },
	{ 0, 5, 1, 0, "Enable low security key" },
	{ 0, 5, 1, 1, "Disable low security key" },
	{ 0, 6, 1, 0, "Do not ignore Secure Boot hardware strap" },
	{ 0, 6, 1, 1, "Ignore Secure Boot hardware strap" },
	{ 0, 7, 1, 0, "Secure Boot Mode: Mode_2" },
	{ 0, 7, 1, 1, "Secure Boot Mode: Mode_PFR" },
	{ 0, 10, 2, 0, "RSA mode : RSA1024" },
	{ 0, 10, 2, 1, "RSA mode : RSA2048" },
	{ 0, 10, 2, 2, "RSA mode : RSA3072" },
	{ 0, 10, 2, 3, "RSA mode : RSA4096" },
	{ 0, 12, 2, 0, "SHA mode : SHA224" },
	{ 0, 12, 2, 1, "SHA mode : SHA256" },
	{ 0, 12, 2, 2, "SHA mode : SHA384" },
	{ 0, 12, 2, 3, "SHA mode : SHA512" },
	{ 0, 14, 1, 0, "Enable patch code" },
	{ 0, 14, 1, 1, "Disable patch code" },
	{ 0, 15, 1, 0, "Enable Boot from Uart" },
	{ 0, 15, 1, 1, "Disable Boot from Uart" },
	{ 0, 16, 6, OTP_REG_VALUE, "Secure Region size (DW): 0x%x" },
	{ 0, 22, 1, 0, "Secure Region : Writable" },
	{ 0, 22, 1, 1, "Secure Region : Write Protect" },
	{ 0, 23, 1, 0, "User Region : Writable" },
	{ 0, 23, 1, 1, "User Region : Write Protect" },
	{ 0, 24, 1, 0, "Configure Region : Writable" },
	{ 0, 24, 1, 1, "Configure Region : Write Protect" },
	{ 0, 25, 1, 0, "OTP strap Region : Writable" },
	{ 0, 25, 1, 1, "OTP strap Region : Write Protect" },
	{ 0, 26, 1, 0, "Copy Boot Image to Internal SRAM" },
	{ 0, 26, 1, 1, "Disable Copy Boot Image to Internal SRAM" },
	{ 0, 27, 1, 0, "Disable image encryption" },
	{ 0, 27, 1, 1, "Enable image encryption" },
	{ 0, 29, 1, 0, "OTP key retire Region : Writable" },
	{ 0, 29, 1, 1, "OTP key retire Region : Write Protect" },
	{ 0, 31, 1, 0, "OTP memory lock disable" },
	{ 0, 31, 1, 1, "OTP memory lock enable" },
	{ 2, 0, 16, OTP_REG_VALUE, "Vender ID : 0x%x" },
	{ 2, 16, 16, OTP_REG_VALUE, "Key Revision : 0x%x" },
	{ 3, 0, 16, OTP_REG_VALUE, "Secure boot header offset : 0x%x" },
	{ 4, 0, 8, OTP_REG_VALID_BIT, "Keys retire : %s" },
	{ 5, 0, 32, OTP_REG_VALUE, "User define data, random number low : 0x%x" },
	{ 6, 0, 32, OTP_REG_VALUE, "User define data, random number high : 0x%x" },
	{ 14, 0, 11, OTP_REG_VALUE, "Patch code location (DW): 0x%x" },
	{ 14, 11, 6, OTP_REG_VALUE, "Patch code size (DW): 0x%x" }
};

static const struct otpconf_info ast1030a1_conf_info[] = {
	{ 0, 1, 1, 0, "Disable Secure Boot" },
	{ 0, 1, 1, 1, "Enable Secure Boot" },
	{ 0, 3, 1, 0, "User region ECC disable" },
	{ 0, 3, 1, 1, "User region ECC enable" },
	{ 0, 4, 1, 0, "Secure Region ECC disable" },
	{ 0, 4, 1, 1, "Secure Region ECC enable" },
	{ 0, 5, 1, 0, "Enable low security key" },
	{ 0, 5, 1, 1, "Disable low security key" },
	{ 0, 6, 1, 0, "Do not ignore Secure Boot hardware strap" },
	{ 0, 6, 1, 1, "Ignore Secure Boot hardware strap" },
	{ 0, 7, 1, 0, "Secure Boot Mode: Normal" },
	{ 0, 7, 1, 1, "Secure Boot Mode: Mode_PFR" },
	{ 0, 10, 4, 0, "Signature Scheme : ECDSA384" },
	{ 0, 10, 4, 1, "Signature Scheme : ECDSA384_RSA2048" },
	{ 0, 10, 4, 2, "Signature Scheme : ECDSA384_RSA3072" },
	{ 0, 10, 4, 3, "Signature Scheme : ECDSA384_RSA4096" },
	{ 0, 10, 4, 4, "Signature Scheme : RSAPSS_2048_SHA256" },
	{ 0, 10, 4, 8, "Signature Scheme : RSAPSS_3072_SHA384" },
	{ 0, 10, 4, 12, "Signature Scheme : RSAPSS_4096_SHA512" },
	{ 0, 10, 4, 5, "Signature Scheme : RSAPKCS1_2048_SHA256" },
	{ 0, 10, 4, 10, "Signature Scheme : RSAPKCS1_3072_SHA384" },
	{ 0, 10, 4, 15, "Signature Scheme : RSAPKCS1_4096_SHA512" },
	{ 0, 14, 1, 0, "Enable patch code" },
	{ 0, 14, 1, 1, "Disable patch code" },
	{ 0, 15, 1, 0, "Enable Boot from Uart" },
	{ 0, 15, 1, 1, "Disable Boot from Uart" },
	{ 0, 16, 6, OTP_REG_VALUE, "Secure Region size (DW): 0x%x" },
	{ 0, 22, 1, 0, "Secure Region : Writable" },
	{ 0, 22, 1, 1, "Secure Region : Write Protect" },
	{ 0, 23, 1, 0, "User Region : Writable" },
	{ 0, 23, 1, 1, "User Region : Write Protect" },
	{ 0, 24, 1, 0, "Configure Region : Writable" },
	{ 0, 24, 1, 1, "Configure Region : Write Protect" },
	{ 0, 25, 1, 0, "OTP strap Region : Writable" },
	{ 0, 25, 1, 1, "OTP strap Region : Write Protect" },
	{ 0, 26, 1, 0, "Copy Boot Image to Internal SRAM" },
	{ 0, 26, 1, 1, "Disable Copy Boot Image to Internal SRAM" },
	{ 0, 27, 1, 0, "Disable image encryption" },
	{ 0, 27, 1, 1, "Enable image encryption" },
	{ 0, 29, 1, 0, "OTP key retire Region : Writable" },
	{ 0, 29, 1, 1, "OTP key retire Region : Write Protect" },
	{ 0, 31, 1, 0, "OTP memory lock disable" },
	{ 0, 31, 1, 1, "OTP memory lock enable" },
	{ 2, 0, 16, OTP_REG_VALUE, "Vender ID : 0x%x" },
	{ 2, 16, 16, OTP_REG_VALUE, "Key Revision : 0x%x" },
	{ 3, 0, 16, OTP_REG_VALUE, "Secure boot header offset : 0x%x" },
	{ 4, 0, 8, OTP_REG_VALID_BIT, "Keys retire : %s" },
	{ 5, 0, 32, OTP_REG_VALUE, "User define data, random number low : 0x%x" },
	{ 6, 0, 32, OTP_REG_VALUE, "User define data, random number high : 0x%x" },
	{ 14, 0, 11, OTP_REG_VALUE, "Patch code location (DW): 0x%x" },
	{ 14, 11, 6, OTP_REG_VALUE, "Patch code size (DW): 0x%x" }
};

#endif
